## This is test deployment for Kubernetes platforms.
## This is _not_ intended to be use in producction.
##
apiVersion: v1
kind: ConfigMap
metadata:
  name: test-wordpress-config
data:
  wordpress-vhosts.conf: |-
    server {
      listen 0.0.0.0:80;
      server_name myapp.example.com;

      root /opt/bitnami/wordpress;
      index index.php;

      location / {
        try_files $uri $uri/ /index.php?q=$uri&$args;
      }

      if (!-e $request_filename)
      {
        rewrite ^/(.+)$ /index.php?q=$1 last;
      }

      location ~ \.php$ {
        fastcgi_pass localhost:9000;
        fastcgi_index index.php;
        fastcgi_param SCRIPT_FILENAME $document_root$fastcgi_script_name;
        include fastcgi_params;
      }
    }
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  labels:
    app: test-mariadb
  name: test-mariadb
spec:
  replicas: 1
  selector:
    matchLabels:
      app: test-mariadb
  template:
    metadata:
      labels:
        app: test-mariadb
    spec:
      containers:
      - image: bitnami/mariadb
        name: test-mariadb
        env:
        - name: MARIADB_USER
          value: bn_wordpress
        - name: MARIADB_DATABASE
          value: bitnami_wordpress
        - name: ALLOW_EMPTY_PASSWORD
          value: "yes"
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  labels:
    app: test-wordpress-nginx
  name: test-wordpress-nginx
spec:
  replicas: 1
  selector:
    matchLabels:
      app: test-wordpress-nginx
  template:
    metadata:
      labels:
        app: test-wordpress-nginx
    spec:
      containers:
      - image: bitnami/wordpress-nginx
        name: test-wordpress-nginx
        env:
        - name: MARIADB_HOST
          value: test-mariadb
        - name: MARIADB_PORT_NUMBER
          value: "3306"
        - name: WORDPRESS_DATABASE_USER
          value: bn_wordpress
        - name: WORDPRESS_DATABASE_NAME
          value: bitnami_wordpress
        - name: ALLOW_EMPTY_PASSWORD
          value: "yes"
        volumeMounts:
        - name: test-wordpress-volumen
          mountPath: /bitnami/nginx/conf/vhosts
      volumes:
        - name: test-wordpress-volumen
          configMap:
            name: test-wordpress-config
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: test-mariadb
  name: test-mariadb
spec:
  ports:
  - port: 3306
    protocol: TCP
    targetPort: 3306
  selector:
    app: test-mariadb
  sessionAffinity: None
  type: ClusterIP
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: test-wordpress-nginx
  name: test-wordpress-nginx
spec:
  ports:
  - port: 8080
    protocol: TCP
    targetPort: 80
  selector:
    app: test-wordpress-nginx
  sessionAffinity: None
  type: ClusterIP
